# Generated by Django 4.1 on 2022-11-26 08:04

from django.db import migrations, models
import django.db.models.deletion
import hand_gesture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.FileField(upload_to="models")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=hand_gesture.models.upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to=hand_gesture.models.upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=5)),
            ],
            options={"unique_together": {("key", "language")},},
        ),
        migrations.CreateModel(
            name="HandGesture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_trained", models.BooleanField(default=False)),
                ("time_create", models.DateTimeField(auto_now_add=True, null=True)),
                ("time_update", models.DateTimeField(auto_now=True, null=True)),
                (
                    "translationKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hand_gesture.translation",
                    ),
                ),
            ],
        ),
    ]
