# Generated by Django 4.1 on 2022-11-30 18:02

from django.db import migrations, models
import hand_gesture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandGesture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation_key", models.CharField(db_index=True, max_length=255)),
                ("is_trained", models.BooleanField(default=False)),
                ("time_create", models.DateTimeField(auto_now_add=True, null=True)),
                ("time_update", models.DateTimeField(auto_now=True, null=True)),
                ("order", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to=hand_gesture.models.upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=5)),
            ],
            options={"unique_together": {("key", "language")},},
        ),
    ]
