# Generated by Django 4.1 on 2022-11-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hand_gesture", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="handgesture", name="order",),
    ]
