# Generated by Django 4.1.3 on 2022-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand_gesture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="handgesture",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="handgesture",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="handgesture",
            name="time_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
