# Generated by Django 4.1.3 on 2022-11-20 09:39

from django.db import migrations, models
import hand_gesture.models


class Migration(migrations.Migration):

    dependencies = [
        ("hand_gesture", "0002_image_alter_handgesture_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to=hand_gesture.models.upload_path
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="handgesture",
            name="is_trained",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=hand_gesture.models.upload_path
            ),
        ),
    ]
