# Generated by Django 4.1 on 2022-11-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hand_gesture", "0003_delete_dataset_delete_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="title",),
    ]
